---
- name: "Deploy Config"
  hosts: juniper
  gather_facts: false

  vars_prompt:
    - name: ansible_user
      prompt: SSH Username
      private: no
    - name: ansible_password
      prompt: SSH Password

  vars:
    gatewayIp: '172.16.0.1'
    radSource: '172.16.0.3'
    mgmtIp: '172.16.0.3/27'
    siteName: 'Montesano'

  tasks:
     - include_tasks: "~/networkAutomation/playbooks/tasks/junos-get-facts.yml"
     - include_tasks: "~/networkAutomation/playbooks/tasks/junos-switch-template.yml"
     - include_tasks: "~/networkAutomation/playbooks/tasks/junos-push-config.yml"  
     - include_tasks: "~/networkAutomation/playbooks/tasks/junos-commit-config.yml"
